### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by milena-kos**
Shortening some stuff, removing video descriptions, moving irrelevant stuff to a new section

### CODE REVIEW

**Comment by Hnedahmotsnalegogur** [comment]
Upvote

**Comment by milena-kos** [comment]
valid

**Comment by Hnedahmotsnalegogur** [comment]
i got no time
i got no time to live
i got no time to live and i cant say goodbye

**Comment by milena-kos** [comment]
ok

**Comment by Hnedahmotsnalegogur** [comment]
ok

**Review by blaumeise20 — APPROVED** [review]
Great thanks

**Pull request merged**
